### PR TITLE
maybe fixed crash when resize vector

### PR DESCRIPTION
**Pull request by 2bbb**
i believe this fix problem #19

### CODE REVIEW

**Comment by 2bbb** [comment]
i reflected a change of #21 and some little changes to this PR.

**Comment by micuat** [comment]
Now there is no osc bound error.

However, when 20 elements are sent and then 10 are sent, receiver's vector still has 20 elements. Is it possible to know how many elements are in the actual vector (this case, 10)?

**Comment by 2bbb** [comment]
i think, if we do resize everytime, we can keep actual vector size.
maybe calling `resize` to make small, is not high cost (i.e. keeps `capacity` and no reallocate).

do you think we should resize?

**Comment by micuat** [comment]
I agree, and I was thinking the same thing.

But I don't know if bad things can happen or not.

**Comment by 2bbb** [comment]
so, we must think about it will limit the usage a little implicitly.
(maybe it will limit anyway.)
i think, we must specified in the document, like this (is constraints i thought.)

* you can't use: `vector<vector<SomeType>> vec`
* you can't use: `vector<SomeType> vec[N]`
* (maybe this is O.K.: `vector<SomeType(&)[N]>`...)

i don't know who use this patterns.

**Comment by micuat** [comment]
I think that is fine. Anyways, it cannot sync `vector<void *>` kind of things because the sender and receiver don't share the same memory. So it makes sense to limit to 1d vector (or `vector<ofVecNf>`).

**Comment by 2bbb** [comment]
okay, first of all, i will do fix to resizing.

**Comment by micuat** [comment]
Works. Sorry for taking long time.

Document still needs update?

**Pull request merged**
