### PR TITLE
fix some problem about publish/subscribe array and vector.

### PR DESCRIPTION
**Pull request by 2bbb**
ping @micuat 

could you check? please! m(_ _)m

### CODE REVIEW

**Comment by micuat** [comment]
I tried but ofxOscPublisher.h gives compile error

    'remove_reference' : ambiguous symbol

at line 233 and 271. I'll look more afterwards.

**Comment by 2bbb** [comment]
what's the current?

**Comment by micuat** [comment]
It compiles but still have same error as before (osc out of range).

**Comment by 2bbb** [comment]
maybe that is in #20

**Comment by micuat** [comment]
@2bbb you are right, I'll see #20 soon as well

**Pull request merged**
